// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Submission struct {
	ID               int64
	SubmissionType   string
	MachineName      string
	CoordinatorModel string
	RunID            pgtype.Text
	Payload          json.RawMessage
	CreatedAt        pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
	PayloadHash      pgtype.Text
}
