// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: q.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (submission_type, machine_name, coordinator_model, run_id, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (submission_type, run_id) WHERE run_id IS NOT NULL DO NOTHING
RETURNING id, submission_type, machine_name, coordinator_model, run_id, payload, created_at
`

type CreateSubmissionParams struct {
	SubmissionType   string
	MachineName      string
	CoordinatorModel string
	RunID            pgtype.Text
	Payload          json.RawMessage
}

// Not idempotent on its own: relies on the partial unique index on (submission_type, run_id)
// WHERE run_id IS NOT NULL. On conflict, does nothing and returns no row -- the caller
// must re-fetch via GetSubmissionByTypeAndRunID to get the existing row. See
// core.CreateReview for the check-then-insert-then-recheck flow (the identity column
// cannot be targeted by ON CONFLICT DO UPDATE SET id = ...).
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.SubmissionType,
		arg.MachineName,
		arg.CoordinatorModel,
		arg.RunID,
		arg.Payload,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.SubmissionType,
		&i.MachineName,
		&i.CoordinatorModel,
		&i.RunID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, submission_type, machine_name, coordinator_model, run_id, payload, created_at FROM submissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.SubmissionType,
		&i.MachineName,
		&i.CoordinatorModel,
		&i.RunID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByTypeAndRunID = `-- name: GetSubmissionByTypeAndRunID :one
SELECT id, submission_type, machine_name, coordinator_model, run_id, payload, created_at FROM submissions WHERE submission_type = $1 AND run_id = $2 LIMIT 1
`

type GetSubmissionByTypeAndRunIDParams struct {
	SubmissionType string
	RunID          pgtype.Text
}

func (q *Queries) GetSubmissionByTypeAndRunID(ctx context.Context, arg GetSubmissionByTypeAndRunIDParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByTypeAndRunID, arg.SubmissionType, arg.RunID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.SubmissionType,
		&i.MachineName,
		&i.CoordinatorModel,
		&i.RunID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, submission_type, machine_name, coordinator_model, run_id, created_at
FROM submissions
WHERE
    ($1::text IS NULL OR submission_type = $1)
    AND ($2::text IS NULL OR machine_name = $2)
    AND ($3::text IS NULL OR coordinator_model = $3)
    AND ($4::timestamptz IS NULL OR created_at >= $4)
    AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY id DESC
LIMIT $7 OFFSET $6
`

type ListSubmissionsParams struct {
	SubmissionType   pgtype.Text
	MachineName      pgtype.Text
	CoordinatorModel pgtype.Text
	Since            pgtype.Timestamptz
	Until            pgtype.Timestamptz
	Offset           int32
	Limit            int32
}

type ListSubmissionsRow struct {
	ID               int64
	SubmissionType   string
	MachineName      string
	CoordinatorModel string
	RunID            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.SubmissionType,
		arg.MachineName,
		arg.CoordinatorModel,
		arg.Since,
		arg.Until,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmissionsRow
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionType,
			&i.MachineName,
			&i.CoordinatorModel,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
